<?php

namespace Database\Seeders;

use App\Models\PlantRecommendationRule;
use Illuminate\Database\Seeder;

class PlantRecommendationRuleSeeder extends Seeder
{
    public function run(): void
    {
        // Sumber: Master_Komoditas_Rehabilitasi_Kehutanan_Jawa_Barat.xlsx
        // Sheet: "RHL Jawa Barat". Seeder dibuat idempotent agar aman dijalankan ulang.
        $rules = [
            [
                'code' => 'RHL-JABAR-01',
                'region_name' => 'Pantura Jabar (Indramayu, Subang, Cirebon)',
                'region_keywords' => ['indramayu', 'subang', 'cirebon'],
                'elevation_min' => 0,
                'elevation_max' => 100,
                'slope_min' => 0,
                'slope_max' => 15,
                'rainfall_min' => 1200,
                'rainfall_max' => 2500,
                'soil_keywords' => ['aluvial', 'grumosol'],
                'land_condition' => 'Datar, rawan degradasi lahan',
                'recommended_plants' => ['Jati', 'Mahoni', 'Sengon', 'Nyamplung', 'Sukun'],
                'category' => 'Kayu & MPTS',
                'rhl_function' => 'Rehabilitasi lahan kering dan produksi',
                'notes' => 'Tanaman tahan kondisi panas dan kering',
                'priority' => 100,
            ],
            [
                'code' => 'RHL-JABAR-02',
                'region_name' => 'Bogor, Bekasi Selatan, Karawang Selatan',
                'region_keywords' => ['bogor', 'bekasi', 'karawang'],
                'elevation_min' => 100,
                'elevation_max' => 500,
                'slope_min' => 0,
                'slope_max' => 25,
                'rainfall_min' => 2000,
                'rainfall_max' => 3500,
                'soil_keywords' => ['latosol', 'podsolik merah kuning', 'podsolik'],
                'land_condition' => 'Datar sampai bergelombang',
                'recommended_plants' => ['Jeruk', 'Mangga', 'Petai', 'Jengkol', 'Sengon', 'Gmelina'],
                'category' => 'MPTS & Kayu',
                'rhl_function' => 'Agroforestri dan konservasi tanah',
                'notes' => 'Cocok untuk lahan masyarakat',
                'priority' => 100,
            ],
            [
                'code' => 'RHL-JABAR-03',
                'region_name' => 'Sukabumi, Cianjur, Bandung Barat',
                'region_keywords' => ['sukabumi', 'cianjur', 'bandung barat'],
                'elevation_min' => 500,
                'elevation_max' => 1000,
                'slope_min' => 8,
                'slope_max' => 30,
                'rainfall_min' => 2500,
                'rainfall_max' => 4500,
                'soil_keywords' => ['andosol', 'latosol vulkanik', 'latosol'],
                'land_condition' => 'Lereng sedang, wilayah hulu DAS',
                'recommended_plants' => ['Jeruk Keprok', 'Durian', 'Alpukat', 'Manggis', 'Petai', 'Sengon', 'Suren'],
                'category' => 'MPTS & Kayu',
                'rhl_function' => 'Rehabilitasi DAS dan peningkatan tutupan lahan',
                'notes' => 'Zona prioritas agroforestri',
                'priority' => 100,
            ],
            [
                'code' => 'RHL-JABAR-04',
                'region_name' => 'Garut, Tasikmalaya, Ciamis Selatan',
                'region_keywords' => ['garut', 'tasikmalaya', 'ciamis'],
                'elevation_min' => 500,
                'elevation_max' => 1200,
                'slope_min' => 15,
                'slope_max' => 40,
                'rainfall_min' => 2500,
                'rainfall_max' => 5000,
                'soil_keywords' => ['andosol', 'regosol', 'latosol'],
                'land_condition' => 'Lereng berbukit',
                'recommended_plants' => ['Durian', 'Alpukat', 'Kemiri', 'Aren', 'Sengon', 'Suren', 'Gmelina'],
                'category' => 'MPTS & Kayu',
                'rhl_function' => 'Pengendalian erosi dan ekonomi masyarakat',
                'notes' => 'Perlu konservasi lereng',
                'priority' => 100,
            ],
            [
                'code' => 'RHL-JABAR-05',
                'region_name' => 'Pegunungan Gede Pangrango, Priangan',
                'region_keywords' => ['bogor', 'sukabumi', 'cianjur', 'bandung', 'garut', 'tasikmalaya', 'sumedang'],
                'elevation_min' => 1000,
                'elevation_max' => 1800,
                'slope_min' => 25,
                'slope_max' => 60,
                'rainfall_min' => 3000,
                'rainfall_max' => 6000,
                'soil_keywords' => ['andosol pegunungan', 'andosol'],
                'land_condition' => 'Curam, fungsi lindung',
                'recommended_plants' => ['Rasamala', 'Puspa', 'Damar', 'Pinus', 'Aren', 'Kemiri'],
                'category' => 'Kayu Konservasi & MPTS',
                'rhl_function' => 'Perlindungan tanah dan air',
                'notes' => 'Prioritas kawasan hulu',
                'priority' => 60,
            ],
            [
                'code' => 'RHL-JABAR-06',
                'region_name' => 'Gunung Ciremai dan pegunungan Kuningan',
                'region_keywords' => ['kuningan', 'majalengka', 'cirebon'],
                'elevation_min' => 800,
                'elevation_max' => 1500,
                'slope_min' => 20,
                'slope_max' => 45,
                'rainfall_min' => 2500,
                'rainfall_max' => 5000,
                'soil_keywords' => ['andosol', 'latosol'],
                'land_condition' => 'Lereng sedang-curam',
                'recommended_plants' => ['Sengon', 'Suren', 'Mahoni', 'Alpukat', 'Durian', 'Petai'],
                'category' => 'Kayu & MPTS',
                'rhl_function' => 'Rehabilitasi hutan rakyat',
                'notes' => 'Mengurangi risiko longsor',
                'priority' => 100,
            ],
            [
                'code' => 'RHL-JABAR-07',
                'region_name' => 'Daerah kritis lahan kering Jawa Barat Selatan',
                'region_keywords' => ['sukabumi', 'cianjur', 'garut', 'tasikmalaya', 'ciamis', 'pangandaran'],
                'elevation_min' => 200,
                'elevation_max' => 800,
                'slope_min' => 15,
                'slope_max' => 45,
                'rainfall_min' => 1500,
                'rainfall_max' => 3000,
                'soil_keywords' => ['podsolik', 'latosol'],
                'land_condition' => 'Kering dan mudah tererosi',
                'recommended_plants' => ['Jati', 'Mahoni', 'Kemiri', 'Jengkol', 'Petai', 'Nyamplung'],
                'category' => 'Kayu & MPTS',
                'rhl_function' => 'Pemulihan lahan terdegradasi',
                'notes' => 'Dipilih berdasarkan ketahanan kekeringan',
                'priority' => 80,
            ],
            [
                'code' => 'RHL-JABAR-08',
                'region_name' => 'Lahan masyarakat sekitar kawasan hutan',
                'region_keywords' => [],
                'elevation_min' => 300,
                'elevation_max' => 1200,
                'slope_min' => 15,
                'slope_max' => 40,
                'rainfall_min' => 2000,
                'rainfall_max' => 4500,
                'soil_keywords' => ['latosol', 'andosol'],
                'land_condition' => 'Agroforestri',
                'recommended_plants' => ['Jeruk', 'Alpukat', 'Durian', 'Manggis', 'Kopi', 'Aren', 'Sengon'],
                'category' => 'MPTS',
                'rhl_function' => 'Peningkatan ekonomi dan tutupan vegetasi',
                'notes' => 'Model kebun campuran',
                'priority' => 10,
            ],
        ];

        foreach ($rules as $rule) {
            PlantRecommendationRule::updateOrCreate(
                ['code' => $rule['code']],
                array_merge($rule, ['is_active' => true])
            );
        }
    }
}
